environment: "local"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  pass: "postgres"
  dbname: "public"
  sslmode: "disable"
  loglevel: 4 # 1 = Silent, 2 = Error, 3 = Warn, 4 = Info

jwt:
  secret: "your-secret-key"
  expiration: 3600 # 1 hour

webservice:
  port: 3200